<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MUNI-VAIO" name="Test2" tests="1" failures="1" timestamp="12 Jan 2019 13:36:47 GMT" time="17.236" errors="0">
  <testcase name="createCustomer" time="0.03" classname="script.Test1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at script.Test1.createCustomer(Test1.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- createCustomer -->
</testsuite> <!-- Test2 -->
